baseURL = "https://wiigg.dev/"
locale = "en-GB"
DefaultContentLanguage = "en"
title = "./wiigg"

summarylength = 50
enableEmoji = true
enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS", "Likes"]

[outputFormats.Likes]
  mediaType = "application/json"
  baseName = "likes"
  isPlainText = true
  notAlternative = true

[module]
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"

[markup]
    [markup.highlight]
        noClasses = false
        codeFences = true
        guessSyntax = true
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80

[params]
customCss = ["css/likes.css", "css/like-counts.css"]
localizedDates = true
indexDateFormat = "2 January 2006"
singleDateFormat = "2 January 2006"
listDateFormat = "2 Jan"
disableTitleCapitalization = true
disableArchiveTitleStyling = true
reversepagetitle = true
mainSections = ["post"]
readMore = true
rssFullContent = true
title = "./wiigg"
author = "Danny Wigg"
description = "Applied AI engineer at OpenAI"
profilePicture = "images/profile.jpg"
images = ["images/social-card.png"]
keywords = "wiigg engineer software azure tech cloud devops kubernetes sustainability green"
favicon = "favicons/"

[services]
  [services.googleAnalytics]
  id = "G-LP9LR8C7GM"

[params.likes]
endpoint = "https://wiigg-likes.wiigg.workers.dev"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/wiigg/"

[[params.socialIcons]]
icon = "fa-brands fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/dannywigg/"

[[params.socialIcons]]
icon = "fa-solid fa-rss"
title = "Subscribe via RSS"
url = "/post/index.xml"

## Menu items
[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"
 
 [[menu.main]]
  name = "About"
  weight = 200
  identifier = "about"
  url = "/about/"
