baseURL = "https://wiigg.dev/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "./wiigg"

# theme as hugo module
#theme = "github.com/lxndrblz/anatole"
# theme as git submodule
theme = "anatole"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "UA-90548533-2"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80

[params]
title = "./wiigg"
author = "Danny Wigg"
description = "Technologist, strategist, engineer"
profilePicture = "images/profile.jpg"
keywords = "wiigg devops engineer cloud native kubernetes sustainability green software tech"
favicon = "favicons/"
customCss = []
gtagId = "G-272395525"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/wiigg/"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/dannywigg/"

[[params.socialIcons]]
icon = "fab fa-mastodon"
title = "Mastodon"
url = "https://mastodonapp.uk/@wiigg"

## Menu items
[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"
 
 [[menu.main]]
  name = "About"
  weight = 200
  identifier = "about"
  url = "/about/"
