baseURL = "https://wiigg.dev/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "./wiigg"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

localizedDates = true

[module]
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80

[params]
title = "./wiigg"
author = "Danny Wigg"
description = "Technologist, strategist, engineer"
profilePicture = "images/profile.jpg"
keywords = "wiigg engineer software azure tech cloud devops kubernetes sustainability green"
favicon = "favicons/"

[services]
  [services.googleAnalytics]
  id = "G-LP9LR8C7GM"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/wiigg/"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/dannywigg/"

## Menu items
[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"
 
 [[menu.main]]
  name = "About"
  weight = 200
  identifier = "about"
  url = "/about/"
